src/Entity/ServiceGroup.php
<?php

namespace App\Entity;

use App\Repository\ServiceGroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServiceGroupRepository::class)]
class ServiceGroup
{
	#[ORM\Id]
	#[ORM\GeneratedValue]
	#[ORM\Column(type: Types::INTEGER)]
	private $id;

	#[ORM\Column(type: Types::STRING, length: 255)]
    private $name;

	#[ORM\Column(type: Types::BOOLEAN)]
    private $public;

	#[ORM\OneToMany(targetEntity: Service::class, mappedBy: 'serviceGroup')]
    private $services;

    public function __construct()
    {
        $this->services = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function isPublic(): ?bool
    {
        return $this->public;
    }

    public function setPublic(bool $public): self
    {
        $this->public = $public;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getServices(): Collection
    {
        return $this->services;
    }


    public function getPublicServices(): Collection
    {
        return $this->getServices()->filter(function (Service $service){
            return $service->isPublic();
        });
    }

    public function addService(Service $service): self
    {
        if (!$this->services->contains($service)) {
            $this->services[] = $service;
            $service->setServiceGroup($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->services->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getServiceGroup() === $this) {
                $service->setServiceGroup(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName();
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Service;
use App\Repository\IncidentRepository;
use App\Repository\ServiceGroupRepository;
use App\Repository\ServiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
	#[Route('/', name: 'app_welcome')]
    public function index(ServiceGroupRepository $repository, ServiceRepository $serviceRepository, IncidentRepository $incidents): Response
    {
        return $this->render('main/index.html.twig', [
            'groups' => $repository->findBy([
                'public' => true
            ]),
            'services' => $serviceRepository,
            'incidents' => $incidents->findLastIncidents()
        ]);
    }

	#[Route('/service/{name}', name: 'app_service_view')]
    public function service(Service $service) : Response
    {
        if(!$service->isPublic() && !$this->isGranted('ROLE_USER')){
            return $this->redirectToRoute('app_login');
        }

        return $this->render('service/index.html.twig', [
            'service' => $service,
            'logs' => $service->getServiceLogs()
        ]);
    }
}

templates/main/incident.html.twig
{% if incident.status == 4 %}
    {% include 'elements/incidents/major.html.twig' with {'incident': incident} %}
{% elseif incident.status == 3 %}
    {% include 'elements/incidents/partial.html.twig' with {'incident': incident}  %}
{% elseif incident.status == 2 %}
    {% include 'elements/incidents/performance.html.twig' with {'incident': incident}  %}
{% elseif incident.status == 1 %}
    {% include 'elements/incidents/operational.html.twig' with {'incident': incident}  %}
{% else %}
    {% include 'elements/incidents/maintenance.html.twig' with {'incident': incident}  %}
{% endif %}

templates/main/index.html.twig
{% extends 'layouts/frontend.html.twig' %}

{% block title %}{{ settingsHelper.general('page_name') }}{% endblock %}

{% block content %}
    {% if settingsHelper.general('dark_mode') == 0 %}
        {% include 'elements/theme_toggle.html.twig' %}
    {% endif %}
    <div class="pt-8">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8" id="status-overview">
            {% include 'main/status_overview.html.twig' with {'services': services} %}
        </div>
    </div>
    {% for group in groups %}
        {% if group.publicServices | length > 0 or is_granted('ROLE_USER') and group.services | length > 0 %}
            <div class="py-5">
                <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
                    <div class="overflow-hidden border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-900 rounded">
                        <div class="rounded-t px-6 py-4 font-semibold text-gray-700 dark:text-gray-400">
                            {{ group.name }}
                        </div>

                        {% for service in (is_granted('ROLE_USER') ? group.services : group.publicServices) %}
                            <div class="py-4 px-6 border-0 border-t border-gray-200 dark:border-gray-700">
                                <div class="flex flex-row justify-items-stretch w-full">
                                    <div class="flex-1">
                                        <span class="text-gray-600 dark:text-gray-400">{{ service.name }}</span>
                                    </div>
                                    <div class="justify-self-start">
                                        <a href="{{ path('app_service_view', {'name': service.name}) }}" class="status-badge" x-service="{{ service.id }}">
                                            {% include 'main/status_badge.html.twig' with {'service': service} %}
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    {% if incidents | length > 0 %}
    <div class="hidden lg:block py-5">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8 pb-10">
           <div class="border-0 border-t-2 border-gray-300 dark:border-gray-600">
               <h1 class="py-2 text-4xl text-gray-600 dark:text-gray-300">{% trans %}Past Incidents{% endtrans %}</h1>
               <div class="border-l-2 mt-10 border-gray-300 dark:border-gray-600">
                   {% for incident in incidents %}
                       {% include 'main/incident.html.twig' with {'incident': incident} %}
                   {% endfor %}
               </div>
           </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/main/status_badge.html.twig
{% if service.currentStatus == 4 %}
    {% include 'elements/status_badges/major.html.twig' with {'id': service.id}%}
{% elseif service.currentStatus == 3 %}
    {% include 'elements/status_badges/partial.html.twig' with {'id': service.id} %}
{% elseif service.currentStatus == 2 %}
    {% include 'elements/status_badges/performance.html.twig' with {'id': service.id} %}
{% elseif service.currentStatus == 1 %}
    {% include 'elements/status_badges/operational.html.twig' with {'id': service.id} %}
{% else %}
    {% include 'elements/status_badges/unknown.html.twig' with {'id': service.id} %}
{% endif %}

templates/main/status_overview.html.twig
{% if services.findAllByState(4) > 0 %}
    {% include 'elements/overview/major.html.twig' with {'text': 'Some systems have major outages'} %}
{% elseif services.findAllByState(3) > 0  %}
    {% include 'elements/overview/partial.html.twig' with {'text': 'Some systems have partial outages'}  %}
{% elseif services.findAllByState(2) > 0  %}
    {% include 'elements/overview/performance.html.twig' with {'text': 'Some systems are having performance issues'} %}
{% else %}
    {% include 'elements/overview/operational.html.twig' with {'text': 'All systems are operational'} %}
{% endif %}